### ISSUE TITLE
A real cloud service?

### ISSUE THREAD

**Issue by cd-FileX** [redsolver/vup#19]
This is rather a question than an issue.

I'm not sure what exactly VUP Cloud Storage is, but if it is a real Cloud Storage, then there has to be a server.
If I'm right it should be s5.ninja, seeming like an instance with only the cloud purpose.
So, for a server there are costs, but if the app is free, there is no data collected and there is no donation link on the website, how is this server being financed?

**Comment by redsolver** [comment]
Hi, currently users are expected to self-host the S5 Node or use one of the storage backends like Pixeldrain (which provides a paid plan) to store files. s5.ninja only provides a very small amount of storage per user, that's why it's free. In the future, there should be multiple independent hosted S5 Node providers which will likely use a combination of small free and paid plans to be sustainable,
